### ISSUE TITLE
Put Frontend Text in Constant Meta

### ISSUE THREAD

**Issue by paanjoe** [govtechmy/go-gov-my#15]
Just like datagovmy, we want to put the text language at 1 place so that we could support translation as well.

- [x] iI8n Translation Services
- [x] Transfer All FE Text to this Meta
- [ ] Bahasa Melayu Text
- [x] English Text
