### ISSUE TITLE
[EPIC] Breakdown what kind of metric need to be traced

### ISSUE THREAD

**Issue by paanjoe** [govtechmy/go-gov-my#347]
### GRAFANA & PROMETHEUS

- [x] http request served (Status Code: 200, 400, 500 ...)
- [x] average request time
- [x] kafka consumer group offset

### OPENTELEMETRY & JAEGER UI
- [x] http request traces
