### ISSUE TITLE
[EPIC] To come out with a User Journey of File Upload feature

### ISSUE THREAD

**Issue by paanjoe** [govtechmy/go-gov-my#384]
There is a demand to have a user upload file / document into storage.

Problem Statement: 
User want to upload and share links to other agencies for file sharing between government to government or even government to citizen.

Requirement: 
- At the dashboard, we can have a button "Create Upload Links" or something link that
- Author are able to manage the link slugs
- We want to have a upload file modal
- We want to have view list of file page
- [KIV] Based on Confidentiality, some document are very sensitive and are not permissible to be uploaded into the cloud, therefore when the user select for Secret or Strictly Confidential, we want to opt out upload those document to the PDSA Government Storage (On-Premise) instead. This will make our apps government compliance.

Tasks:

- [ ] UI/UX Flow for File Upload & Sharing features
- [ ] [FE] Admin: List of file / storage uploaded within agencies
- [ ] [FE] View shared uploaded files page
- [ ] [FE] Create links and upload files modal
- [ ] [FE] Analytics for File Upload
- [ ] #403
- [ ] [BE] Lists of MimeType allowed using enums
- [ ] [BE] Encryption Decryption logic
- [ ] #402
